from typing import Callable, Any


def run_forever() -> None: ...


class TactixActor:
    def __init__(self, _cb: Callable) -> None: ...

    def send(self, event: str, message: Any) -> None: ...

    def send_later(self, event: str, message: Any, delay: float) -> None: ...

    def shutdown(self) -> None: ...
